### ISSUE TITLE
framework.rancher-cli path missing

### ISSUE THREAD

**Issue by mashwino** [kdebisschop/rundeck-rancher-node-plugin#25] opened 2020-02-10 23:39 UTC
Thank you once for your work.
I encounter a little problem with the last version, due to the need to have the rancher_cli. Documentation says that both can be use, cli and api, but it keeps saying that it did not find the framework.rancher-cli path. I'm not a devellopper at all, more a sysadmin, and I had a look on the code to see if I could find a clue, and I found it, at least I found how to workaround:
file: RancherFileCopier.java
I comment out those 3 lignes:
   145          //if (searchPath == null) {
   146            //  searchPath = framework.getProperty(FMWK_RANCHER_CLI_PATH);
   147          //}

Hope this helps.

**Comment by kdebisschop** [comment] 2020-02-11 14:13
This is a duplicate of issue #21 that was has already been resolved. Try release 0.7.10 -- if that does not resolve the issue for you, feel free to reopen this issue.

**Closed as completed by kdebisschop** 2020-02-11 14:13 UTC
